---
- name: Check if package {{ package_name }} is installed
  raw: "dpkg -s {{ package_name }} >/dev/null 2>&1"
  register: cmd_check
  changed_when: false
  failed_when: false

- name: Install missing packages
  become: yes
  raw: |
    apt-get update && apt-get install -y {{ package_name }}
  when:
    - cmd_check.rc != 0
