---
- name: Check if package {{ package_name }} is installed
  raw: "rpm -q {{ package_name }}"
  register: cmd_check
  changed_when: false
  failed_when: false

- name: Install missing packages
  raw: |
    dnf install -y {{ package_name }}
  when:
    - cmd_check.rc != 0
