#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-bootstrap

- name: Run tasks to detect SSH Port
  ansible.builtin.include_tasks: detect_sshd_port.yml
  when: ansible_connection | default("ssh") in ["ssh", "paramiko"]

- name: Detect package manager
  raw: |
    if command -v dnf5 >/dev/null 2>&1; then
      echo dnf5
    elif command -v dnf >/dev/null 2>&1; then
      echo dnf
    elif command -v yum >/dev/null 2>&1; then
      echo yum
    elif command -v apt-get >/dev/null 2>&1; then
      echo apt
    elif command -v zypper >/dev/null 2>&1; then
      echo zypper
    else
      echo unknown
    fi
  register: pkg_mgr_check
  changed_when: false

- name: Save package manager
  set_fact:
    bootstrap_pkg_mgr: "{{ pkg_mgr_check.stdout | trim }}"

- name: Check for packages
  include_tasks: "{{ bootstrap_pkg_mgr }}_check_and_install.yml"
  loop: "{{ _bootstrap_packages[bootstrap_pkg_mgr] }}"
  loop_control:
    loop_var: package_name

- name: Reset connection to use installed Python
  meta: reset_connection
