---
- name: Converge bootstrap role
  hosts: all
  gather_facts: false
  vars:
    bootstrap_detect_ssh_port: false
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      tags:
        - bootstrap
        - install
